name: CodingGuidelines Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 6 * * 1
env:
  version: 0.1.9
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Use latest NuGet
      uses: nuget/setup-nuget@v1
    - name: Get Directory
      run: pwd
    - name: Dotnet Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild 'IntelliTect.Analyzer.sln' /p:configuration='Release' /p:Version=${{ env.version }}
    # - name: Build
    #   run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet pack
      run: dotnet pack -p:Version="${{ env.version }}-ci-${{ github.run_id }}" -o ${{ github.workspace }}
      shell: powershell
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}
        name: drop