name: CodingGuidelines Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  version: 0.1.9
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 5.0
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0.x'
    - name: Get Directory
      run: pwd
    - name: Build
      run: dotnet build -p:Version="${{ env.version }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet pack
      run: dotnet pack -p:Version="${{ env.version }}-ci-${{ github.run_number }}" -o ${{ github.workspace }}
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/*.nupkg
        name: drop